### PR TITLE
Update/ember 3.0 syntax

### LINKED ISSUE #25: Deprecation in ember-cli 2.18?
Hi, getting the following Deprecation warning while running `ember server` on ember-cli 2.18

> DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   DependencyVersionChecker.NPMDependencyVersionChecker (/Users/snorvell/code/cne/alt-versions/player-frontend-ALT/node_modules/ember-export-application-global/node_modules/ember-cli-version-checker/index.js:137:32)

Thanks!

### PR DESCRIPTION
**Pull request by ScottLNorvell**
Hi @rwjblue,

After noticing that #26's tests did not pass on Ember 3.0, I finally found time try and update them. Basically I did a diff of a completely new `ember addon ember-export-application-global` and updated things accordingly. It was a good chance to learn the new testing format!  The tests at least pass locally for me, so I'll soon see if they pass on travis. A couple of notes:

- This fixes #25 
- We can close #26 in favor of this
- I went ahead and added yarn since I noticed ember cli uses it. (I put it in a separate commit in case it's not desired)
- I haven't updated the version in light of the update to Ember 3.0. I was pretty sure this was more than just a patch update, but I wasn't sure if it made sense to bump it to 2.1 or all the way up to 3.0 to match Ember. I'll defer to your expertise.

Thanks again for your help with #25 and I look forward to any feedback!

### CODE REVIEW

**Comment by olleolleolle** [comment]
This updates ember-cli-babel, also, super! Can it be merged?

**Comment by Turbo87** [comment]
idk, this changes too many things to be reasonably reviewable for me

**Comment by rwjblue** [comment]
Could use a rebase now that some of the other things that @Turbo87 	mentioned have been addressed as separate PRs...

**Comment by bertdeblock** [comment]
Going to close this, as I don't think we will be updating this addon.

**Pull request closed without merging**
