### PR TITLE
Add `exportApplicationGlobalAs` to the config

### PR DESCRIPTION
**Pull request by knownasilya**
`exportApplicationGlobalAs: 'GlobalName'`

### CODE REVIEW

**Comment by knownasilya** [comment]
Ping

**Comment by knownasilya** [comment]
Ping

**Comment by rwjblue** [comment]
Can we use the same `exportApplicationGlobal` config variable for both things?  If its a string use that for the global name, if `true` infer the global name from the app name (as we do now), otherwise do nothing.

**Comment by knownasilya** [comment]
Good idea. Will make the change.

**Comment by stefanpenner** [comment]
> Good idea. Will make the change.
>  Show all checks

@knownasilya I plan to release a new version today, if you can sneak this in shortly we can include this :)

**Comment by knownasilya** [comment]
Will work it out once I get home :)

**Comment by stefanpenner** [comment]
> Will work it out once I get home :)

:+1:

**Comment by knownasilya** [comment]
All set.

**Comment by stefanpenner** [comment]
thanks :)

**Pull request merged**
